[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]


[build]
target = "llvm_target_descp.json"

#using cargo run (add .exe extension)
[target.'cfg(target_os="none")']
runner = "bootimage runner"
